GET http://localhost:8080/api/scry/cards?q=mistbinder
###

GET http://localhost:8080/api/names
###

POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "adam.metal@codecool.com",
  "password": "12345"
}

###
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "email": "adam.metal@codecool.com",
  "password": "12345"
}

###
GET http://localhost:8080/api/auth/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0ubWV0YWxAY29kZWNvb2wuY29tIiwiX2lkIjoiNjMyOTgwNzM3MjI2YjkwNDQ3M2YwNjZkIiwiaWF0IjoxNjY0MTkxMDgxfQ.ugzuV0hF3ghpuApl5CgStXQZRDGoKvcFWF5yuoAHC9E

###
GET http://localhost:8080/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0ubWV0YWwrMUBjb2RlY29vbC5jb20iLCJfaWQiOiI2MzI5ODEyNWQ5ODliMjFkYjA4YzNmNzciLCJpYXQiOjE2NjM3NDMxNDR9.exfd4BF1a-nDV268xDshiX1mnsLRPdgENYHefHrfBtY

###
GET http://localhost:8080/api/user/decks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0ubWV0YWxAY29kZWNvb2wuY29tIiwiX2lkIjoiNjMyOTgwNzM3MjI2YjkwNDQ3M2YwNjZkIiwiaWF0IjoxNjY0MTkxMDgxfQ.ugzuV0hF3ghpuApl5CgStXQZRDGoKvcFWF5yuoAHC9E

###
GET http://localhost:8080/api/user/decks/63298b5abc605f10aa997460
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0ubWV0YWwrMUBjb2RlY29vbC5jb20iLCJfaWQiOiI2MzI5ODEyNWQ5ODliMjFkYjA4YzNmNzciLCJpYXQiOjE2NjM4NjEzMjh9.FcGS03y0VhvQB2o2mTtH6RtXzrtpebRYCnI53hXkIrI


###
POST http://localhost:8080/api/user/decks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0ubWV0YWxAY29kZWNvb2wuY29tIiwiX2lkIjoiNjMyOTgwNzM3MjI2YjkwNDQ3M2YwNjZkIiwiaWF0IjoxNjY0MTkxMDgxfQ.ugzuV0hF3ghpuApl5CgStXQZRDGoKvcFWF5yuoAHC9E
Content-Type: application/json

{
  "name": "Mono Raaad"
}
