GET http://localhost:8080/api/scry/cards?q=mistbinder
###

GET http://localhost:8080/api/names
###

POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "adam.metal+1@codecool.com",
  "password": "12345"
}

###
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "email": "adam.metal+1@codecool.com",
  "password": "12345"
}

###
GET http://localhost:8080/api/auth/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0ubWV0YWwrMUBjb2RlY29vbC5jb20iLCJfaWQiOiI2MzI5ODEyNWQ5ODliMjFkYjA4YzNmNzciLCJpYXQiOjE2NjM4NjEzMjh9.FcGS03y0VhvQB2o2mTtH6RtXzrtpebRYCnI53hXkIrI

###
GET http://localhost:8080/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0ubWV0YWwrMUBjb2RlY29vbC5jb20iLCJfaWQiOiI2MzI5ODEyNWQ5ODliMjFkYjA4YzNmNzciLCJpYXQiOjE2NjM3NDMxNDR9.exfd4BF1a-nDV268xDshiX1mnsLRPdgENYHefHrfBtY

###
GET http://localhost:8080/api/user/decks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0ubWV0YWwrMUBjb2RlY29vbC5jb20iLCJfaWQiOiI2MzI5ODEyNWQ5ODliMjFkYjA4YzNmNzciLCJpYXQiOjE2NjM4NjEzMjh9.FcGS03y0VhvQB2o2mTtH6RtXzrtpebRYCnI53hXkIrI

###
GET http://localhost:8080/api/user/decks/63298b5abc605f10aa997460
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0ubWV0YWwrMUBjb2RlY29vbC5jb20iLCJfaWQiOiI2MzI5ODEyNWQ5ODliMjFkYjA4YzNmNzciLCJpYXQiOjE2NjM4NjEzMjh9.FcGS03y0VhvQB2o2mTtH6RtXzrtpebRYCnI53hXkIrI


###
POST http://localhost:8080/api/user/decks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0ubWV0YWwrMUBjb2RlY29vbC5jb20iLCJfaWQiOiI2MzI5ODEyNWQ5ODliMjFkYjA4YzNmNzciLCJpYXQiOjE2NjM3NDMxNDR9.exfd4BF1a-nDV268xDshiX1mnsLRPdgENYHefHrfBtY
Content-Type: application/json

{
  "name": "Mono Raaad"
}
